### ISSUE TITLE
Window x64 editor

### ISSUE THREAD

**Issue by timi-liuliang** [timi-liuliang/echo#179]

**Comment by rikazukun** [comment]
This would be nice. I am currently checking on the engine and trying to make game(s). I'd love to help make echo grow.

**Comment by ghost** [comment]
This would be nice. I am currently checking on the engine and trying to make game(s). I'd love to help make echo grow. I'll try to make some tutorials / guides as of now.

**Comment by timi-liuliang** [comment]
My dear dear Rikazukun.  you are the first person who comments the Echo project.  and you also the first person who submit some issues of Echo. And definitely, you are also the first person who wants to help Echo grow.

 I'm so happy about that,  Which means I'm no longer alone. At last, I have some friends like you to communicate with. To learn from each other.

 I'm also very happy that you are trying to make games by Echo. But I have to say, for now, the Echo isn't functioning enough. But you can tell me which types of games will you make(2d or 3d)?
which is the first platform will you game deployment on(ios, android, html5, windows, mac...)?
Then we can rearrange the Echo development tasks for your game.

**Comment by ghost** [comment]
Yes, currently Echo isn't functioning properly (lots of bugs yet) but it is still doable, and it has a lot of promise/future. Currently I am focusing on 2D, since making a 3D game has a lot of complexity, and configuring/programming it's core takes a lot of time. Basing from the examples completing a 2D game can be accomplished even with the current build.

As for other stuffs, I would like to start managing the wiki, correcting some information and such.

Do you have some kind of a chat application / website you use? Like discord? It'll be faster to talk with that.

Good job on making Echo~

**Comment by timi-liuliang** [comment]
This is the discord server I just created.
https://discord.gg/HWhjwYU

But Discord was blocked in my country. I can only use it by chrome now.
I am looking for a solution......

**Comment by ghost** [comment]
I see, that is unfortunate; we can use anything you want for chat and such. To rely information faster.

**Comment by timi-liuliang** [comment]
My Wechat user name is "79402005".  Or you can scan this  QR code by Wechat.
![](https://github.com/blab-liuliang/resume/blob/master/wechat.jpeg?raw=true)
